# Generated by Django 3.2 on 2021-04-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thumb',
        ),
    ]
